name: Setup

description: Checkout repository & install dependencies

runs:
  using: composite
  steps:
    - uses: volta-cli/action@v4
    - run: yarn install --immutable
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: bundle exec pod install
      working-directory: ios
      shell: bash

    - run: bundle exec pod install
      working-directory: example/ios
      shell: bash
