nodeLinker: node-modules
nmHoistingLimits: workspaces
packageExtensions:
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": "*"
      "typescript": "*"
  "@commitlint/cli@*":
    peerDependencies:
      "@types/node": "*"
      "typescript": "*"
  "@react-native-community/eslint-config@*":
    peerDependencies:
      "typescript": "*"
  "@react-native/eslint-config@*":
    peerDependencies:
      "typescript": "*"
  "@react-native/babel-plugin-codegen@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@react-native/babel-preset@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@react-native/metro-babel-transformer@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@react-native/community-cli-plugin@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@react-native/metro-config@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      "typescript": "*"
  "eslint-plugin-jest@*":
    peerDependencies:
      "typescript": "*"
  "babel-plugin-transform-flow-enums@*":
    peerDependencies:
      "@babel/core": "*"
  "react-native@*":
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
