require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

target 'ReactAirplay' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])

  pod 'SwiftLint'
end
