name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        required: false
        type: boolean

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Configure git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set npm token
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - run: yarn install --immutable
      - run: npx pod-install
      - run: yarn install --immutable
        working-directory: example

      - run: yarn typescript
      - run: yarn lint
      - run: yarn build
      - run: yarn release ${{ fromJSON(github.event.inputs.dryRun) && '--dry-run' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
